# -*- coding: utf-8 -*-
"""poultry_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XTS4yODODkk8pHJxwrPvtqj8gV-u2wI6
"""

!pip install roboflow

import os
from google.colab import drive
drive.mount('/content/drive')

!mkdir '/content/drive/My Drive/yolov8'

from roboflow import Roboflow

rf = Roboflow(api_key="LTpT6Qjy7cU4K0MGGjVk")
project = rf.workspace("litter-raking-project").project("smart-poultry-farm-litter-raking")
version = project.version(3)
dataset = version.download("yolov8")

!pip install ultralytics

from ultralytics import YOLO

model =YOLO("yolov8m.pt")

!yolo task=detect mode=train model=yolov8m.pt data=/content/smart-poultry-farm-litter-raking-3/data.yaml epochs=5 batch=8 plots=True

!ls /content/runs/detect/train2

from IPython.display import Image

Image(filename="/content/runs/detect/train2/confusion_matrix.png",width=600)

Image(filename='/content/runs/detect/train2/results.png',width=600)

Image(filename='/content/runs/detect/train2/train_batch1.jpg',width=600)

"""#validate Custome Model

"""

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('/content/runs/detect/train2/weights/best.pt')  # load a custom model

# Validate the model
metrics = model.val()  # no arguments needed, dataset and settings remembered
metrics.box.map    # map50-95
metrics.box.map50  # map50
metrics.box.map75  # map75
metrics.box.maps   # a list contains map50-95 of each category

!yolo task=detect mode=val model=/content/runs/detect/train2/weights/best.pt data=/content/smart-poultry-farm-litter-raking-3/data.yaml

"""#predict

"""

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('/content/runs/detect/train2/weights/best.pt')  # load a custom model

# Predict with the model
results = model('/content/smart-poultry-farm-litter-raking-3/train/images/0-2-_jpg.rf.02e88fed0d8745205b4b8152cd4dfc3c.jpg')

"""#inference with Custom Model

"""

!yolo task=detect mode=predict model=/content/runs/detect/train2/weights/best.pt conf=0.25 source=/content/smart-poultry-farm-litter-raking-3/test/images save=True

infer =YOLO("/content/runs/detect/train2/weights/best.pt")

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('/content/runs/detect/train2/weights/best.pt')  # load a custom trained model

# Export the model
model.export(format='onnx')

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg')[12:50]:
      display(Image(filename=image_path, width=600))
      print("\n")



